# Generated by Django 5.1.4 on 2024-12-12 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneSensori', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letture',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sensori',
            options={'managed': False},
        ),
    ]
